### ISSUE TITLE
PDD Requirement Analysis

### ISSUE THREAD

**Issue by djkykp** [djkykp/Project_DSE#1]
> Analysis of requirements for the configuration of development board.

**Comment by djkykp** [comment]
I added the PDD document with the requirements

**Comment by djkykp** [comment]
Make a system description of the DSE Project.

**Comment by YairGomez** [comment]
PDD version 9 was added

**Comment by djkykp** [comment]
PDD version was added to the repository and was approved by Mentor Sofia Ponce.
