### ISSUE TITLE
Modules Configuration

### ISSUE THREAD

**Issue by djkykp** [djkykp/Project_DSE#4]
> Refer to Data Sheet
> Internal MCU Clock configuration (8)
> Configure ADC Module
> Configure SPI for LCD Module (13)
> Configure PWM Module (8)
> Configure Interrup IRQ (5)

**Comment by RafaelIglesias** [comment]
Needed modules will be uploaded. ADC, Interruption, Timer, PWM

**Comment by RafaelIglesias** [comment]
Modules added to repository.

**Comment by djkykp** [comment]
The modules was tested in class and all modules works fine.
