### ISSUE TITLE
Documentation of Verification Testing

### ISSUE THREAD

**Issue by djkykp** [djkykp/Project_DSE#6]
> Refer to datasheet.
> Use APIs to confirm proper operation.
> Make a proper test to verify the correct functionality.
> Update Documentation

**Comment by jesusdjxx52** [comment]
The elaboration of test document. 
This document help me for validation of requirement.

**Comment by djkykp** [comment]
The document was analized by Jesus Lara and Jesus Castillo and was approved by the mentor Sofia Ponce. The documment was uploaded to the repository with the "commit 7abe920c5e16a3bb98381908634940a394e877f8"
